parameters:
  - name: DeployStageVariableMappings
    type: object
    default: {}
  - name: Environment
    type: string
    default: "dev"
  - name: condition
    type: string
    default: "succeeded()"
  - name: dependsOn
    type: object
    default: {}
   
stages:
  - stage: Deploy_${{ parameters.Environment }}
    displayName: "Deploy ${{ parameters.Environment }}"
    condition: ${{ parameters.condition }}
    dependsOn:
      - ${{ each dependsOnThis in parameters.dependsOn }}:
          - ${{ dependsOnThis }}
    variables:
      - ${{ each DeployStageVariableMapping in parameters.DeployStageVariableMappings }}:
          - name: ${{ DeployStageVariableMapping.Key }}
            value: ${{ replace(DeployStageVariableMapping.Value, '[ENV]', parameters.Environment) }}

    jobs:
      - deployment: deployApp
        displayName: "Deploy to ${{ parameters.Environment }}"
        environment: "$(AzDOEnvironment)"
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: "BuiltWebService"
                  displayName: "Download BuiltWebService artifact"

                - download: current
                  artifact: "PowershellArtifact"
                  displayName: "Download PowerShell artifact"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Deploy"
                  inputs:
                    azureSubscription: ${{ variables.azureSubscriptionServiceConnection }}
                    WebAppName: $(WebAppResourceName)
                    deployToSlotOrASE: true
                    resourceGroupName: $(WebAppResourceGroupName)
                    SlotName: "staging"
                    packageForLinux: "$(Pipeline.Workspace)/**/BuiltWebService.zip"
                    enableCustomDeployment: true
                    DeploymentType: "zipDeploy"
                    TakeAppOfflineFlag: false
                    JSONFiles: "**/appsettings.json"

                - task: PowerShell@2
                  displayName: "Check the status of Service"
                  inputs:
                    targetType: filePath
                    filePath: "$(Pipeline.Workspace)/PowershellArtifact/CheckServiceStatus.ps1"
                    arguments: "-healthEndPointUrl $(HealthCheckUrl) -waitTimeInMinute 5"
